# Generated by Django 3.2.6 on 2022-10-01 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(blank=True, default=None, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuotas', models.FloatField(blank=True, default=None, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
