# Generated by Django 3.2.6 on 2022-10-21 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
